name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  examle-job:
    runs-on: centos-latest
    steps:
      - name: Print a welcome message
        run: echo "Welcome to our first GA Workflow"
