name: JS Test

on:
    push:
        paths:
            - "src/**"
        branches:
            - main
            - "release/**"
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "18"

            - run: chmod +x test.sh

            - run: ./test.sh
